---
abstract: "Internationalization for DBIx::Class ResultSet'ss"
author:
  - 'Diego Kuperman, C<< <diego at freekeylabs.com > >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Class-I18NColumns
no_index:
  directory:
    - inc
    - t
requires:
  DBICx::TestDatabase: 0
  DBIx::Class: 0
  DBIx::Class::ForceUTF8: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.01
